# Generated by Django 4.1.6 on 2023-02-11 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="name",
            new_name="sender_name",
        ),
    ]
